# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-26 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OCMShare',
        ),
        migrations.DeleteModel(
            name='OCMShareReceived',
        ),
    ]
