# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-26 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocm', '0002_auto_20191126_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCMShare',
            fields=[
                ('share_secret', models.CharField(db_index=True, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('from_user', models.CharField(db_index=True, max_length=255)),
                ('to_user', models.CharField(db_index=True, max_length=255)),
                ('to_server_url', models.URLField()),
                ('repo_id', models.CharField(db_index=True, max_length=36)),
                ('repo_name', models.CharField(max_length=255)),
                ('path', models.TextField()),
                ('permission', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=25, unique=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ocm_share',
            },
        ),
        migrations.CreateModel(
            name='OCMShareReceived',
            fields=[
                ('share_secret', models.CharField(db_index=True, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('from_user', models.CharField(db_index=True, max_length=255)),
                ('to_user', models.CharField(db_index=True, max_length=255)),
                ('from_server_url', models.URLField()),
                ('repo_id', models.CharField(db_index=True, max_length=36)),
                ('repo_name', models.CharField(max_length=255)),
                ('path', models.TextField()),
                ('permission', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=25, unique=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ocm_share_received',
            },
        ),
    ]
