# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-26 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocm', '0003_ocmshare_ocmsharereceived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocmshare',
            old_name='share_secret',
            new_name='shared_secret',
        ),
        migrations.RenameField(
            model_name='ocmsharereceived',
            old_name='share_secret',
            new_name='shared_secret',
        ),
        migrations.AlterField(
            model_name='ocmshare',
            name='permission',
            field=models.CharField(choices=[('rw', 'read, write'), ('r', 'read'), ('admin', 'admin'), ('preview', 'preview on web, cannot download'), ('cloud-edit', 'preview on web, can edit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ocmsharereceived',
            name='permission',
            field=models.CharField(choices=[('rw', 'read, write'), ('r', 'read'), ('admin', 'admin'), ('preview', 'preview on web, cannot download'), ('cloud-edit', 'preview on web, can edit')], max_length=50),
        ),
    ]
