# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-28 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocm', '0004_auto_20191126_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocmshare',
            name='token',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='ocmsharereceived',
            name='token',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
