# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-28 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocm', '0005_auto_20191128_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocmshare',
            name='path',
        ),
        migrations.RemoveField(
            model_name='ocmsharereceived',
            name='path',
        ),
    ]
