# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-29 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocm', '0006_auto_20191128_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocmshare',
            name='path',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ocmsharereceived',
            name='path',
            field=models.TextField(default=''),
        ),
    ]
